### ISSUE TITLE
How to skip a field in prost?

### ISSUE THREAD

**Issue by lz1998** [tokio-rs/prost#708] opened 2022-08-16 09:00 UTC
https://serde.rs/field-attrs.html#skip

**Comment by LucioFranco** [comment] 2022-08-16 16:29
I do not believe this is currently a feature of prost, so will need to be RFC and added.

**Comment by commonsensesoftware** [comment] 2024-11-15 01:32
Duplicate of #174 where I've added an example of the use case.

The scenarios seem to be very straight forward:

1. If you code generate from a `*.proto` file there is no change since skipping a field means simply not defining it
2. Skipping it with explicit attribute annotations can be done one of a few possible ways:
    a. Use `#[prost(skip)]` to be congruent with `serde`
    b. Use `#[prost(ignore)]` which is a different word with the same meaning
    c. Simply ignore any field without an annotation as every field requires an explicit annotation (e.g. if `#[prost]` is missing, ignore it)

**Comment by caspermeijn** [comment] 2024-11-20 08:24
I agree this is a duplicate of #174

**Closed by caspermeijn** 2024-11-20 08:24 UTC
Labels: enhancement
