### ISSUE TITLE
Provide enum -> string methods

### ISSUE THREAD

**Issue by vriesk** [tokio-rs/prost#654] opened 2022-05-24 13:26 UTC
Hi,

Google ProtoBuf implementations provide a way to get the string value out of PB enums. For example, the C++ generated code provides:

```
const std::string& SomeEnum_Name(T enum_t_value) { ... }
```

This is especially useful for things like metric label values and such. Would it be possible to provide this functionality with Prost?

Would you accept a PR for this?

**Comment by LucioFranco** [comment] 2022-05-24 16:15
All generated types should implement _atleast_ `Debug` which you can use for metrics https://docs.rs/prost-types/latest/prost_types/value/enum.Kind.html#trait-implementations

**Comment by vriesk** [comment] 2022-05-24 16:19
That does not cut it, because:
 - `Debug` is considered to be used for debugging purposes and not for later programmatic use (also, I don't think there's a notion of a contract making it stable over time)
 - The enum values are camelcasized, not like the original enum values; if I wanted to keep the same behaviour as other languages, I would need to RE_CAPITALIZE it back, which is likely error prone.

**Comment by vriesk** [comment] 2022-05-24 16:24
Oh, there's even explicit lack of stability contract for derived `Debug`s:

https://doc.rust-lang.org/std/fmt/trait.Debug.html#stability

Even if Prost does promise stable `Debug` on its types, it's not a convention to expect it so and will be confusing.

**Comment by LucioFranco** [comment] 2022-05-24 18:47
Right, the issue is that https://doc.rust-lang.org/stable/std/macro.stringify.html# might change. 

I would be open to hearing a proposal on how you would solve this. I am keen to try to keep anything added to as light as possible.

**Comment by vriesk** [comment] 2022-05-26 11:25
So, assuming we have this enum definition:

```
enum E {
  GOOD = 1;
  BAD = 2;
  MAYBE = 3;
}
```

I would imagine the following code would be emitted:

```
[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
enum E {
    Bad = 1,
    Good = 2,
    Maybe = 3,
}
impl E {
    fn to_str_name(&self) -> &'static str {
        match self {
            E::Bad => "BAD",
            E::Good => "GOOD",
            E::Maybe => "MAYBE",
        }
    }
}
```
(unsure if that would be explicit in the generated code or could happen through derive)


Now, this adds the overhead for those static strings which might be substantial for some long enums. I therefore think it might make sense to add this generated mappings based on a default-false config flag.

WDYT?

**Comment by LucioFranco** [comment] 2022-05-26 14:44
Could we leverage `Display` instead of an inherent method? In addition, I would imagine we need to support this at the `prost-derive` level rather than `prost-build` so Im also not sure how we pass that data down without using something like `stringify!` which is the root of the problem here anyways.

**Comment by vriesk** [comment] 2022-05-26 15:04
`Display` is for user-facing stuff, not programmatic use.

I might be not that familiar with all the intervals, but if we approach this they way I wrote above with the explicit `to_str_name()` in the generated code, `prost-derive` won't be needed and all the magic will need to happen in https://github.com/tokio-rs/prost/blob/master/prost-build/src/code_generator.rs

**Comment by danburkert** [comment] 2022-05-26 15:13
I agree that enum values should impl ‘Display’.  https://github.com/tokio-rs/prost/pull/558/files#diff-cf7e8d404551aa946887ea800d3794724e4dc39fe008474b86a375633d3da870R357 Contains an implementation of that, one option is to extract that and land it independently.  That PR also impls FromStr which is also often useful.

**Comment by danburkert** [comment] 2022-05-26 15:14
@vriesk 

> Display is for user-facing stuff, not programmatic use.

can you expand on that thought?  I’m not sure what that distinction means in the context of rust.

**Comment by vriesk** [comment] 2022-05-26 21:00
@danburkert looking now at the PR you have mentioned, the `to_string()` method is not an implementation of `Display` and, since it does not undergo camelcasing transformations, it would be the value I'm looking for: https://github.com/tokio-rs/prost/pull/558/files#diff-cf7e8d404551aa946887ea800d3794724e4dc39fe008474b86a375633d3da870R358

The problem there though is that it needlessly returns `String` rather than `&'static str`.

**Comment by LucioFranco** [comment] 2022-05-27 06:59
Yeah, I guess we would need to add an api to provide a `&'static str` and there isn't really a built in trait for it. I think I would be happy to accept a PR that adds a method similar to the one in the c++ version for enums.

**Comment by vriesk** [comment] 2022-05-27 17:20
@LucioFranco, here you go: https://github.com/tokio-rs/prost/pull/659

**Comment by LucioFranco** [comment] 2022-06-08 17:00
#659 merged, this can be closed now. Thanks!

**Closed by LucioFranco** 2022-06-08 17:00 UTC
