### ISSUE TITLE
"you are deriving `PartialEq` and can implement `Eq`" warning when building autogenerated code using the `nightly` toolchain

### ISSUE THREAD

**Issue by fidencio** [tokio-rs/prost#670] opened 2022-06-22 11:48 UTC
When using the `nightly` toolchain, which we use as part of our CI, the code that's autogenerated by prost fails to build due to "you are deriving `PartialEq` and can implement `Eq`".

Here's an example of the CI failing due to the error mentioned above:
```
error: you are deriving `PartialEq` and can implement `Eq`
Error:  --> /home/runner/work/image-rs/image-rs/target/debug/build/image-rs-47f333f263432d68/out/getresource.rs:1:17
  |
1 | #[derive(Clone, PartialEq, ::prost::Message)]
  |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
  |
  = note: `-D clippy::derive-partial-eq-without-eq` implied by `-D warnings`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
error: you are deriving `PartialEq` and can implement `Eq`
Error:   --> /home/runner/work/image-rs/image-rs/target/debug/build/image-rs-47f333f263432d68/out/getresource.rs:10:17
   |
10 | #[derive(Clone, PartialEq, ::prost::Message)]
   |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
error: could not compile `image-rs` due to 2 previous errors
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```
Source: https://github.com/confidential-containers/image-rs/runs/7002574404?check_suite_focus=true

**Comment by LucioFranco** [comment] 2022-06-22 15:52
Duplicate of https://github.com/tokio-rs/prost/issues/661

**Closed by LucioFranco** 2022-06-22 15:52 UTC
