### ISSUE TITLE
Consistent JSON serialisation

### ISSUE THREAD

**Issue by rollo-b2c2** [tokio-rs/prost#1000] opened 2024-03-13 11:04 UTC
I'm having some issues consistently converting Prost types to JSON.

Now, I know you can use serde to serialize these types with some build.rs magic, but the issue with serde serialisation is that it's not quite consistent with the canonical proto JSON serialisation.

**Comment by caspermeijn** [comment] 2024-05-16 15:10
This seems to be a duplicate of #75. Please re-open is that is not correct.

Help is wanted for implementing JSON support.

**Closed by caspermeijn** 2024-05-16 15:10 UTC
